// Mocks generated by Mockito 5.4.6 from annotations
// in teste_ws_work_flutter/test/features/cars/presentation/bloc/lead_bloc_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:teste_ws_work_flutter/core/errors/failures.dart' as _i6;
import 'package:teste_ws_work_flutter/features/lead/domain/entities/lead.dart'
    as _i8;
import 'package:teste_ws_work_flutter/features/lead/domain/repositories/lead_repository.dart'
    as _i2;
import 'package:teste_ws_work_flutter/features/lead/domain/usecases/get_leads.dart'
    as _i7;
import 'package:teste_ws_work_flutter/features/lead/domain/usecases/save_lead.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: deprecated_member_use
// ignore_for_file: deprecated_member_use_from_same_package
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: must_be_immutable
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeLeadRepository_0 extends _i1.SmartFake
    implements _i2.LeadRepository {
  _FakeLeadRepository_0(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(Object parent, Invocation parentInvocation)
    : super(parent, parentInvocation);
}

/// A class which mocks [SaveLead].
///
/// See the documentation for Mockito's code generation for more information.
class MockSaveLead extends _i1.Mock implements _i4.SaveLead {
  MockSaveLead() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LeadRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLeadRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LeadRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, void>> call(_i4.SaveLeadParams? params) =>
      (super.noSuchMethod(
            Invocation.method(#call, [params]),
            returnValue: _i5.Future<_i3.Either<_i6.Failure, void>>.value(
              _FakeEither_1<_i6.Failure, void>(
                this,
                Invocation.method(#call, [params]),
              ),
            ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, void>>);
}

/// A class which mocks [GetLeads].
///
/// See the documentation for Mockito's code generation for more information.
class MockGetLeads extends _i1.Mock implements _i7.GetLeads {
  MockGetLeads() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.LeadRepository get repository =>
      (super.noSuchMethod(
            Invocation.getter(#repository),
            returnValue: _FakeLeadRepository_0(
              this,
              Invocation.getter(#repository),
            ),
          )
          as _i2.LeadRepository);

  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i8.Lead>>> call() =>
      (super.noSuchMethod(
            Invocation.method(#call, []),
            returnValue:
                _i5.Future<_i3.Either<_i6.Failure, List<_i8.Lead>>>.value(
                  _FakeEither_1<_i6.Failure, List<_i8.Lead>>(
                    this,
                    Invocation.method(#call, []),
                  ),
                ),
          )
          as _i5.Future<_i3.Either<_i6.Failure, List<_i8.Lead>>>);
}
